# -*- coding: utf-8 -*-

IMAGES_FOLDER = "..\..\..\outputs\images"

DEFAULT_PARAMS_CONSTANT = { "s_0": 5,
                            "x_0": 0,
                            "q_0": 1,
                            "nbSimu": 1,
                            "nb_iter": 100,
                            "nb_episode": 2000,
                            "window_size": 600,
                            "time_step": 0.01,
                            "size_q": 80,
                            "q_max": 2,
                            "T_max": 1,
                            "mu": 1,
                            "alpha": 0.1,
                            "var": 1,
                            "kappa" : 0.1,
                            "phi": 1,
                            "A": 0.25,
                            "gamma": 0.05,
                            "pctg_min": 0.001,
                            "print_metrics": False,
                            "print_freq": 600
                            }

DEFAULT_PARAMS_PASS = { "s_0": 5,
                        "x_0": 0,
                        "q_0": 1,
                        "nbSimu": 1,
                        "nb_iter": 100,
                        "nb_episode": 2000,
                        "window_size": 600,
                        "time_step": 0.01,
                        "size_q": 80,
                        "q_max": 2,
                        "T_max": 1,
                        "mu": 1,
                        "alpha": 0.1,
                        "alpha_min": 1,
                        "alpha_max": 3,
                        "r": 2/3,
                        "var": 1,
                        "kappa" : 0.1,
                        "phi": 1,
                        "A": 0.25,
                        "gamma": 0.05,
                        "pctg_min": 0.001,
                        "print_metrics": False,
                        "print_freq": 600
                        }


DEFAULT_PARAMS_SAGA = { "s_0": 5,
                        "x_0": 0,
                        "q_0": 1,
                        "nbSimu": 1,
                        "nb_iter": 100,
                        "nb_episode": 2000,
                        "window_size": 600,
                        "time_step": 0.01,
                        "size_q": 80,
                        "q_max": 2,
                        "T_max": 1,
                        "mu": 1,
                        "alpha": 0.1,
                        "var": 1,
                        "kappa" : 0.1,
                        "phi": 1,
                        "n_max": 1,
                        "prob_exp": 1,
                        "A": 0.25,
                        "gamma": 0.05,
                        "pctg_min": 0.001,
                        "print_metrics": False,
                        "print_freq": 600
                        }